### ISSUE TITLE
Cannot find example ocean grid files

### ISSUE THREAD

**Issue by jbusecke** [adcroft/regrid_runoff#5]
I am trying to follow the example notebook but I am unable to retrieve the example ocean grid files:
```
fetch_file_from_web('ftp://ftp.gfdl.noaa.gov/home/aja/OM4_05_grid.unpacked/ocean_hgrid.nc')
fetch_file_from_web('ftp://ftp.gfdl.noaa.gov/home/aja/OM4_05_grid.unpacked/ocean_static.nc')
```
Did these files get moved to a new location or are they not available anymore?

**Comment by adcroft** [comment]
They did get moved when the ftp server was rebuilt earlier this year. The
correct paths are in
https://github.com/adcroft/regrid_runoff/blob/master/.travis.yml . I think
I re-ran the notebook in the same work space so the downloaded files where
in place and the fetch function did not need to do anything. Thanks for
spotting that.
